[[templates]]
name = "test"
description = "Created via Wizard"
execution_mode = "Click"

[templates.monitor_region]
x = 0.0
y = 0.0
width = 1920.0
height = 1080.0

[templates.matching]
file = "template.png"
threshold = 0.8999999761581421

[templates.action.Click]
offset = [
    10,
    10,
]
