# Ruff設定ファイル - 自動リフォーマット用

# 基本設定
target-version = "py311"
line-length = 88
include = ["src/**/*.py", "tests/**/*.py", "main.py"]
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "archive",
]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
]

ignore = [
    "E501",  # line-too-long (blackが処理)
    "E203",  # whitespace-before-punctuation (blackと競合)
    "B008",  # function-call-in-default-argument
    "F401",  # unused-import (条件付きインポートで必要)
]

[format]
# フォーマット設定
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.isort]
# インポート整理設定
force-single-line = true
known-first-party = ["src"]

[lint.per-file-ignores]
# ファイル別の例外設定
"tests/**/*.py" = ["B011", "E999"]  # テストでの例外を緩和、Python3.8構文エラーを無視
"main.py" = ["E402"]                # メインファイルでのインポート順序を緩和
